before_script:
  - rm -rf  $(pwd)/toolscollection_builds
  - mkdir  $(pwd)/toolscollection_builds

allpackage:
  script:
    - /Applications/Unity/Hub/Editor/2018.1.0b5/Unity.app/Contents/MacOS/Unity -projectPath $(pwd) -logFile ./log.txt -batchmode -executeMethod PackageDesigner.CommandLineExportAllPackage  $(pwd)/toolscollection_builds
  only:
    - master
  tags:
    - unity-editor
